{% set name = "forestopenfermion" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/forestopenfermion-{{ version }}.tar.gz
  sha256: a47fd36619ea1cbb973dce33d1716b83e988d8b0acaa97d4bb94ddec7eda50ff

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >={{ python_min }}
  run:
    - numpy >=1.0.0,<2.0.0
    - openfermion <1.0.0
    - pyquil >=2.0.0,<3.0.0
    - python >={{ python_min }}
    - grove <2.0.0
    - scipy >=1.0.0,<2.0.0

test:
  imports:
    - forestopenfermion
  commands:
    - pip check
  requires:
    - pip
    - python >={{ python_min }}

about:
  home: https://pypi.org/project/forestopenfermion/
  summary: A plugin allowing OpenFermion to interface with Forest.
  description: |
    OpenFermion is an open source package for compiling and analyzing quantum
    algorithms that simulate fermionic systems. This plugin library allows the
    circuit construction and simulation environment Forest to interface with OpenFermion.
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/rigetti/forest-openfermion

extra:
  recipe-maintainers:
    - BastianZim
